targets:
  $default:
    builders:
      json_serializable:
        options:
          # https://pub.dev/packages/json_serializable#annotation-values

          # MethodChannel中传递的Map是Map<dynamic, dynamic>的
          any_map: true

          # checked: false
          # constructor: ""
          # create_factory: true
          # create_to_json: true
          # disallow_unrecognized_keys: false

          # Bean.toString()里面执行toJson时, 需要toJson也执行内部Bean的toJson
          explicit_to_json: true

          # field_rename: none
          # generic_argument_factories: false
          # ignore_unannotated: false
          # include_if_null: true
