// Autogenerated from Pigeon (v3.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.amap.flutter.amap_flutter_search;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class GeneratedAMapSearchApis {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class QueryPoiResult {
    private @Nullable Map<String, Object> result;
    public @Nullable Map<String, Object> getResult() { return result; }
    public void setResult(@Nullable Map<String, Object> setterArg) {
      this.result = setterArg;
    }

    private @NonNull Long code;
    public @NonNull Long getCode() { return code; }
    public void setCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"code\" is null.");
      }
      this.code = setterArg;
    }

    /** Constructor is private to enforce null safety; use Builder. */
    private QueryPoiResult() {}
    public static final class Builder {
      private @Nullable Map<String, Object> result;
      public @NonNull Builder setResult(@Nullable Map<String, Object> setterArg) {
        this.result = setterArg;
        return this;
      }
      private @Nullable Long code;
      public @NonNull Builder setCode(@NonNull Long setterArg) {
        this.code = setterArg;
        return this;
      }
      public @NonNull QueryPoiResult build() {
        QueryPoiResult pigeonReturn = new QueryPoiResult();
        pigeonReturn.setResult(result);
        pigeonReturn.setCode(code);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("result", result);
      toMapResult.put("code", code);
      return toMapResult;
    }
    static @NonNull QueryPoiResult fromMap(@NonNull Map<String, Object> map) {
      QueryPoiResult pigeonResult = new QueryPoiResult();
      Object result = map.get("result");
      pigeonResult.setResult((Map<String, Object>)result);
      Object code = map.get("code");
      pigeonResult.setCode((code == null) ? null : ((code instanceof Integer) ? (Integer)code : (Long)code));
      return pigeonResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class SearchHostApiCodec extends StandardMessageCodec {
    public static final SearchHostApiCodec INSTANCE = new SearchHostApiCodec();
    private SearchHostApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return QueryPoiResult.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof QueryPoiResult) {
        stream.write(128);
        writeValue(stream, ((QueryPoiResult) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface SearchHostApi {
    @NonNull String getPlatformVersion();
    void setApiKey(@NonNull String apiKey);
    void updatePrivacyShow(@NonNull Boolean isContains, @NonNull Boolean isShow);
    void updatePrivacyAgree(@NonNull Boolean isAgree);
    void queryPoi(Result<QueryPoiResult> result);

    /** The codec used by SearchHostApi. */
    static MessageCodec<Object> getCodec() {
      return SearchHostApiCodec.INSTANCE;
    }

    /** Sets up an instance of `SearchHostApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, SearchHostApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.SearchHostApi.getPlatformVersion", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              String output = api.getPlatformVersion();
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.SearchHostApi.setApiKey", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String apiKeyArg = (String)args.get(0);
              if (apiKeyArg == null) {
                throw new NullPointerException("apiKeyArg unexpectedly null.");
              }
              api.setApiKey(apiKeyArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.SearchHostApi.updatePrivacyShow", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              Boolean isContainsArg = (Boolean)args.get(0);
              if (isContainsArg == null) {
                throw new NullPointerException("isContainsArg unexpectedly null.");
              }
              Boolean isShowArg = (Boolean)args.get(1);
              if (isShowArg == null) {
                throw new NullPointerException("isShowArg unexpectedly null.");
              }
              api.updatePrivacyShow(isContainsArg, isShowArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.SearchHostApi.updatePrivacyAgree", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              Boolean isAgreeArg = (Boolean)args.get(0);
              if (isAgreeArg == null) {
                throw new NullPointerException("isAgreeArg unexpectedly null.");
              }
              api.updatePrivacyAgree(isAgreeArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.SearchHostApi.queryPoi", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              Result<QueryPoiResult> resultCallback = new Result<QueryPoiResult>() {
                public void success(QueryPoiResult result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.queryPoi(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
