// Autogenerated from Pigeon (v3.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class AmapApiResult;

@interface AmapApiResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithData:(nullable NSDictionary<NSString *, id> *)data
    message:(nullable NSString *)message
    code:(NSNumber *)code;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, id> * data;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, strong) NSNumber * code;
@end

/// The codec used by AmapSearchHostApi.
NSObject<FlutterMessageCodec> *AmapSearchHostApiGetCodec(void);

@protocol AmapSearchHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setApiKeyApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)updatePrivacyShowIsContains:(NSNumber *)isContains isShow:(NSNumber *)isShow error:(FlutterError *_Nullable *_Nonnull)error;
- (void)updatePrivacyAgreeIsAgree:(NSNumber *)isAgree error:(FlutterError *_Nullable *_Nonnull)error;
- (void)searchPoiPageNum:(NSNumber *)pageNum pageSize:(NSNumber *)pageSize query:(NSString *)query types:(NSString *)types city:(NSString *)city location:(nullable id)location boundRadius:(nullable NSNumber *)boundRadius isDistanceSort:(NSNumber *)isDistanceSort extensions:(NSString *)extensions completion:(void(^)(AmapApiResult *_Nullable, FlutterError *_Nullable))completion;
- (void)regeocodePoint:(id)point radius:(NSNumber *)radius latLngType:(NSString *)latLngType extensionType:(NSString *)extensionType poiTypes:(NSString *)poiTypes mode:(NSString *)mode completion:(void(^)(AmapApiResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void AmapSearchHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AmapSearchHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
