// Autogenerated from Pigeon (v3.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "GeneratedAMapSearchApis.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface AmapApiResult ()
+ (AmapApiResult *)fromMap:(NSDictionary *)dict;
+ (nullable AmapApiResult *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation AmapApiResult
+ (instancetype)makeWithData:(nullable NSDictionary<NSString *, id> *)data
    message:(nullable NSString *)message
    code:(NSNumber *)code {
  AmapApiResult* pigeonResult = [[AmapApiResult alloc] init];
  pigeonResult.data = data;
  pigeonResult.message = message;
  pigeonResult.code = code;
  return pigeonResult;
}
+ (AmapApiResult *)fromMap:(NSDictionary *)dict {
  AmapApiResult *pigeonResult = [[AmapApiResult alloc] init];
  pigeonResult.data = GetNullableObject(dict, @"data");
  pigeonResult.message = GetNullableObject(dict, @"message");
  pigeonResult.code = GetNullableObject(dict, @"code");
  NSAssert(pigeonResult.code != nil, @"");
  return pigeonResult;
}
+ (nullable AmapApiResult *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [AmapApiResult fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"data" : (self.data ?: [NSNull null]),
    @"message" : (self.message ?: [NSNull null]),
    @"code" : (self.code ?: [NSNull null]),
  };
}
@end

@interface AmapSearchHostApiCodecReader : FlutterStandardReader
@end
@implementation AmapSearchHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [AmapApiResult fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface AmapSearchHostApiCodecWriter : FlutterStandardWriter
@end
@implementation AmapSearchHostApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[AmapApiResult class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface AmapSearchHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation AmapSearchHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[AmapSearchHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[AmapSearchHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *AmapSearchHostApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    AmapSearchHostApiCodecReaderWriter *readerWriter = [[AmapSearchHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void AmapSearchHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AmapSearchHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.getPlatformVersion"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlatformVersionWithError:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(getPlatformVersionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getPlatformVersionWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.setApiKey"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setApiKeyApiKey:error:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(setApiKeyApiKey:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_apiKey = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setApiKeyApiKey:arg_apiKey error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.updatePrivacyShow"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updatePrivacyShowIsContains:isShow:error:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(updatePrivacyShowIsContains:isShow:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_isContains = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_isShow = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api updatePrivacyShowIsContains:arg_isContains isShow:arg_isShow error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.updatePrivacyAgree"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(updatePrivacyAgreeIsAgree:error:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(updatePrivacyAgreeIsAgree:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_isAgree = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api updatePrivacyAgreeIsAgree:arg_isAgree error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.searchPoi"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(searchPoiPageNum:pageSize:query:types:city:center:radiusInMeters:isDistanceSort:extensions:completion:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(searchPoiPageNum:pageSize:query:types:city:center:radiusInMeters:isDistanceSort:extensions:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_pageNum = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_pageSize = GetNullableObjectAtIndex(args, 1);
        NSString *arg_query = GetNullableObjectAtIndex(args, 2);
        NSString *arg_types = GetNullableObjectAtIndex(args, 3);
        NSString *arg_city = GetNullableObjectAtIndex(args, 4);
        id arg_center = GetNullableObjectAtIndex(args, 5);
        NSNumber *arg_radiusInMeters = GetNullableObjectAtIndex(args, 6);
        NSNumber *arg_isDistanceSort = GetNullableObjectAtIndex(args, 7);
        NSString *arg_extensions = GetNullableObjectAtIndex(args, 8);
        [api searchPoiPageNum:arg_pageNum pageSize:arg_pageSize query:arg_query types:arg_types city:arg_city center:arg_center radiusInMeters:arg_radiusInMeters isDistanceSort:arg_isDistanceSort extensions:arg_extensions completion:^(AmapApiResult *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SearchHostApi.regeocode"
        binaryMessenger:binaryMessenger
        codec:AmapSearchHostApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(regeocodePoint:radius:latLngType:extensionType:poiTypes:mode:completion:)], @"AmapSearchHostApi api (%@) doesn't respond to @selector(regeocodePoint:radius:latLngType:extensionType:poiTypes:mode:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        id arg_point = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_radius = GetNullableObjectAtIndex(args, 1);
        NSString *arg_latLngType = GetNullableObjectAtIndex(args, 2);
        NSString *arg_extensionType = GetNullableObjectAtIndex(args, 3);
        NSString *arg_poiTypes = GetNullableObjectAtIndex(args, 4);
        NSString *arg_mode = GetNullableObjectAtIndex(args, 5);
        [api regeocodePoint:arg_point radius:arg_radius latLngType:arg_latLngType extensionType:arg_extensionType poiTypes:arg_poiTypes mode:arg_mode completion:^(AmapApiResult *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
